config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "tools#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # To generate nested paths
  resources :tools do
    resources :bookings, only: %i[new create]
  end

  resources :bookings, only: %i[index show edit update destroy]
  get '/my_tools', to: 'tools#my_tools', as: :my_tools

  # get '/accept/:id', to: 'bookings#accept', as: :accept_booking
  # get '/decline/:id', to: 'bookings#decline', as: :decline_booking
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :tool
  belongs_to :user

  enum status: {
    accepted: 0
    # accepted: 1,
    # declined: 2
  }
  validates :starting_date, :end_date, presence: true
end

app/models/tool.rb
class Tool < ApplicationRecord
  belongs_to :user
  # has_many :users
  has_many :bookings, dependent: :destroy

  has_one_attached :photo

  validates :name, :tool_type, :price, :description, :location, :photo, presence: true

  # Geocode
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  # PG Search
  include PgSearch::Model
  pg_search_scope :search_by_name_tool_type_and_location, # Name of our scope
    against: [ :name, :tool_type, :location ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings
  has_many :tools
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end

  def show
    @booking = Booking.find(params[:id])
    @tool = @booking.tool # grabs tool_id
  end

  def new
    @tool = Tool.find(params[:tool_id]) # grab id
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.tool_id = params[:tool_id]
    @booking.user = current_user

    if @booking.save
      redirect_to bookings_path(@booking.tool)
    else
      render :new, status: :unprocessable_entity
    end
  end

  # def accept
  #   @booking = Booking.find(params[:id])
  #   @booking.status = 1

  #   if @booking.save
  #     redirect_to bookings_path(current_user)
  #   else
  #     render :new, status: :unprocessable_entity
  #   end
  # end

  # def decline
  #   @booking = Booking.find(params[:id])
  #   @booking.status = 2

  #   if @booking.save
  #     redirect_to bookings_path(current_user)
  #   else
  #     render :new, status: :unprocessable_entity
  #   end
  # end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.user = current_user
    if @booking.update(booking_params)
      redirect_to booking_path(@booking), notice: "Your booking was successfully updated"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    # raise
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path, status: :see_other
  end

  private

  def booking_params
    params.require(:booking).permit(:starting_date, :end_date, :tool_id, :user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  # before_action :set_tool, except: :destroy
  skip_before_action :authenticate_user!, only: %i[index show]

  #GET
  def index
    if params[:query].present?
      @tools = Tool.search_by_name_tool_type_and_location(params[:query])
    else
      @tools = Tool.all
    end

    @markers = @tools.geocoded.map do |tool|
      {
        lat: tool.latitude,
        lng: tool.longitude
      }
    end
  end

  # GET
  def show
    @tool = Tool.find(params[:id])

    # Geocoder: provides coordinates for all our tools instances
    @markers = [lat: @tool.latitude, lng: @tool.longitude]
  end

  # GET
  def new
    @tool = Tool.new
  end

  # POST
  def create
    @tool = Tool.new(tool_params)
    @tool.user = current_user
    if @tool.save
      redirect_to my_tools_path, notice: "Your tool was successfully added!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  # GET
  def edit
    @tool = Tool.find(params[:id])
  end

  # PATCH
  def update
    @tool = Tool.find(params[:id])
    @tool.user = current_user
    if @tool.update(tool_params)
      redirect_to my_tools_path, notice: "Your tool was successfully updated"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @tool = Tool.find(params[:id])

    @tool.destroy
    redirect_to my_tools_path, notice: "Your tool was successfully removed.", status: :see_other
  end

  def my_tools
    @my_tools = Tool.where(user: current_user)
  end

  private

  def set_tool
    @tool = Tool.find(params[:id])
  end

  def tool_params
    params.require(:tool).permit(:name, :tool_type, :price, :description, :location, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<%= render "shared/navbar" %>
<div class="container-fluid mt-3" style="display: flex; justify-content:center; align-items: center;">
<div style="width: 50%;">
  <h1 class="mb-3 mt-3">🧰 Request to add <%= @tool.name %> to your Toolbox</h1>

  <%= simple_form_for [@tool, @booking] do |f| %>
    <%= f.input :starting_date, html5: true %>
    <%= f.input :end_date, html5: true %>
    <%= f.submit %>
  <% end %>

  <%= link_to "Cancel", tools_path %>
</div>
</div>

app/views/bookings/end_date:date.html.erb
<h1>Bookings#end_date:date</h1>
<p>Find me in app/views/bookings/end_date:date.html.erb</p>

app/views/bookings/index.html.erb
<div class="booking-index-master">

  <%= render "shared/navbar" %>

  <h1>🏷 Your requested tools to rent...</h1>

  <ul class="list-unstyled">
    <% @bookings.each do |booking| %>
      <li>
        <div style="background-color: white; width: 100% !important;" class="card-holder">
          <%# Card image div %>

          <div class="card-category" style="width: auto; heigth:100%;">
            <%= cl_image_tag booking.tool.photo.key, height: 200, width: 200, crop: :fill %>
          </div>


            <div class="card-info">
              <ul class="list-unstyled text-start">
                <li>
                  <%= link_to booking.tool.name, booking_path(booking) %>
                </li>


                <li>
                    <%= booking.status %>
                </li>
                <%# if booking.status === 'pending' %>
                <%# link_to 'Accept', accept_booking_path(booking) %> <%# link_to 'Decline', decline_booking_path(booking) %>
                <%# end %>

                <li>
                  <%= link_to "Edit Booking", edit_booking_path(booking) %>
                </li>

                <li>
                  <%= link_to "Cancel Booking",
                    booking_path(booking),
                    data: { turbo_method: :delete, turbo_confirm: "🛠 Are you sure you want to cancel this booking?"},
                    :style=>'font-size: 0.8rem; color: #d66767; text-decoration: none;'
                  %>
                </li>
              </ul>
          </div>
        </div>
      </li>
    <% end %>
  </ul>

  <%= link_to "Back to tools", tools_path  %>
</div>

app/views/bookings/new.html.erb
<%= render "shared/navbar" %>
<%# <div class="container-fluid"> %>
<div class="container-fluid mt-3" style="display: flex; justify-content:center; align-items: center;">
<div style="width: 50%;">
  <h1 class="mb-3 mt-3">🧰 Request to add <%= @tool.name %> to your Toolbox</h1>

  <%# Nested form!!! 🔴 %>
  <%= simple_form_for [@tool, @booking] do |f| %>
    <%= f.input :starting_date, html5: true %>
    <%= f.input :end_date, html5: true %>
    <%= f.submit %>
  <% end %>

  <%= link_to "Cancel", tools_path %>
</div>
</div>

app/views/bookings/show.html.erb
<%# 🪝 I can see whether my request is approved or not %>
<%= render "shared/navbar" %>

<div class="container-fluid">
<h1>🛠 <%= @tool.name %></h1>

<img src="<%= cl_image_path @tool.photo.key %>" alt="image of tool listing" style="width: 500px; height: auto; border-radius: 10px;">

<h2>$<%= @tool.price %> <span style="font-size: 1rem; color: gray;">/ per day</span></h2>

<ul class="list-unstyled">
  <li>Category: <%= @tool.tool_type %></li>
  <li>Description: <%= @tool.description %></li>
  <li>Location: <%= @tool.location %></li>
</ul>

<h3>Request</h3>
<ul class="list-unstyled">
  <li>Start date: <%= @booking.starting_date.strftime('%a, %b %e %Y') %></li>
  <li>End date: <%= @booking.end_date.strftime('%a, %b %e %Y')  %></li>
</ul>

<h3>Status</h3>
<p style="color: gray;">Pending</p>

 <%= link_to "Cancel booking",
      booking_path(@booking),
      data: { turbo_method: :delete, turbo_confirm: "🛠 Are you sure you want to cancel this booking?" }
    %>

<%= link_to "Back to your pending tools", bookings_path  %>

<%= link_to "Back to tools", tools_path  %>
</div>

app/views/bookings/starting_date:date.html.erb
<h1>Bookings#starting_date:date</h1>
<p>Find me in app/views/bookings/starting_date:date.html.erb</p>

app/views/bookings/status:integer.html.erb
<h1>Bookings#status:integer</h1>
<p>Find me in app/views/bookings/status:integer.html.erb</p>

app/views/bookings/tool:references.html.erb
<h1>Bookings#tool:references</h1>
<p>Find me in app/views/bookings/tool:references.html.erb</p>

app/views/bookings/user:references.html.erb
<h1>Bookings#user:references</h1>
<p>Find me in app/views/bookings/user:references.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tuulkit</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <%# MAPBOX %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
  </head>

  <body>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<%# <h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p> %>

<%= render "shared/banner" %>
<%= render "shared/carousel" %>

app/views/shared/_banner.html.erb
<div class="banner">
  <div class="d-flex flex-column">
    <h1>T U U L K I T</h1>
    <p><em>The <strong>right tools</strong> for the <strong>right price!</strong></em></p>
    <%# <a class="btn btn-danger" href="#">Let's build!</a> %>
    <%= link_to "Let's build!", new_user_registration_path, class: "btn btn-danger" %>
  </div>
</div>

app/views/shared/_carousel.html.erb
<div class="card-holder">
  <% @tools.each do |t| %>
  <div class="d-flex flex-column m-3">
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path t.photo.key %>)">
    </div>
    <div class="carousel-card">
      <ul>
          <li>
            <%=link_to t.name, tool_path(t) %>
          </li>
          <%# <li>
           <%= link_to "Book",  new_tool_booking_path(t), class:"btn btn-success"%>
          <%# </li> %>
      </ul>
    </div>
  </div>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_index.html.erb
<div class="index-master">
    <div class="index-card">
        <% @tools.each do |t| %>
        <div class="d-flex flex-column m-3">
            <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
        </div>
        <ul>
          <li>
            <%=link_to t.name, tool_path(t) %>
          </li>
          <li>
            <%= link_to "Book",  new_tool_booking_path(t), class:"btn btn-success"%>
          </li>
        </ul>
    </div>
  </div>

app/views/shared/_navbar.html.erb
<div class="navbar sticky-top navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid d-flex">
    <a class="navbar-brand" href="/">
      <%= image_tag "helmet.png"%>
    </a>

    <div class="search">
      <%= form_with url: tools_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control border-end-0 border searchbar",
          id: "example-search-input",
          placeholder: "Search Tools"

        %>
        <div class="input-group-append">
           <%= button_tag(type: "submit", class: "btn btn-outline-secondary") do %>
              <i class="fa fa-search"></i>
           <% end %>
        </div>
      <% end %>
   </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">

          <li class="nav-item dropdown">
          <%= image_tag "toolbox.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My Toolkit", my_tools_path, class: "dropdown-item" %>
              <%= link_to "My Bookings", bookings_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
          <!--li class="nav-item"-->
          <!--/li-->
      </ul>
    </div>
  </div>
</div>

app/views/shared/_show.html.erb
<div class="card-trip">
  <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" />
  <div class="card-trip-infos">
    <div>
      <h2>Title here</h2>
      <p>Short description here!</p>
    </div>
    <h2 class="card-trip-pricing">£99.99</h2>
    <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" />
  </div>
</div>

app/views/tools/edit.html.erb
<%= render "shared/navbar" %>
<div class="container-fluid mt-3" style="display: flex; justify-content:center; align-items: center;">
<div style="width: 50%;">
<h1 class="mb-3 mt-3">Edit Tool</h1>

<%= simple_form_for @tool do |f| %>
  <%= f.input :name, as: :text %>
  <%= f.input :tool_type, as: :text %>
  <%= f.input :price, as: :integer %>
  <%= f.input :description, as: :text %>
  <%= f.input :user_id %>
  <%= f.input :location, as: :text%>
  <%# t.index ["user_id"], name: "index_tools_on_user_id" %>
  <%= f.submit 'Submit', class: 'btn btn-secondary' %>
<% end %>

<%= link_to "Cancel", my_tools_path %>
</div>
</div>

app/views/tools/index.html.erb
<div class="index-master">
  <%= render "shared/navbar" %>
  <%= render "shared/banner" %>
  <div class="carousel-master">
  <%= render "shared/carousel" %>
  </div>

  <div class="index-container">
    <div class="row">

    </div>
  </div>
  <div class="map col-12">
    <div id="map"
        style="width: 100%; height: 50vh; border: 1px solid lightgray; border-radius: 5px;"
        data-controller="map"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
        data-map-markers-value="<%= @markers.to_json %>"
    >
    </div>
  </div>
</div>

app/views/tools/my_tools.html.erb
<div class="my-tools-master">
  <%= render "shared/navbar" %>
  <h1>My tools for rent</h1>

    <%= link_to "List a new tool", new_tool_path  %>

    <% @my_tools.each do |t| %>
    <div class="d-flex flex-column m-3">
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path t.photo.key %>)">
      </div>
      <div class="card-info">
        <ul>

            <li>
              <%=link_to t.name, tool_path(t) %>
            </li>
            <li>
            <%= link_to "Edit",  edit_tool_path(t), class:"btn btn-success"%>
            </li>
        </ul>

        <%= link_to "Delete a tool", tool_path(t),
        data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this tool?"},
        :style=>'font-size: 0.8rem; color: #d66767; text-decoration: none;'
      %>

      </div>
    </div>
  </div>
  <% end %>

  <%= link_to "Back to tools", tools_path  %>

app/views/tools/new.html.erb
<%= render "shared/navbar" %>
<div class="container-fluid mt-3" style="display: flex; justify-content:center; align-items: center;">
<div style="width: 50%;">
<h1 class="mb-3 mt-3">List your Tool</h1>

<%= simple_form_for @tool do |f| %>
  <%= f.input :name, as: :text %>
  <%= f.input :tool_type, as: :text %>
  <%= f.input :price, as: :integer %>
  <%= f.input :description, as: :text %>
  <%= f.input :location, as: :text%>
  <%# upload pic %>
  <%= f.input :photo, as: :file %>

  <%= f.submit 'Submit', class: 'btn btn-secondary' %>
<% end %>

<%= link_to "Cancel", my_tools_path %>
</div>
</div>

app/views/tools/show.html.erb
<%= render "shared/navbar" %>
<div class="show-master">
    <div class="container">
        <div class="card-trip">
            <%= cl_image_tag @tool.photo.key %>
            <div class="card-info">
                <h2><%= @tool.name %></h2>
            <div class="card-trip-pricing">
                <h3><%= @tool.price %>$</h3>
                <%= link_to 'Book this tool', new_tool_booking_path(@tool), class: 'book-button' %>
            </div>

            </div>
        </div>
        <div class="descrip-with-map" <p="">Easy to operate - Full range 40-225 amp selector switch quickly sets the welding current and ensures a uniform arc each and every time you weld<p></p>
              <div class="map col-12">
                <div id="map"
                    style="width: 100%; height: 50vh; border: 1px solid lightgray; border-radius: 5px;"
                    data-controller="map"
                    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
                    data-map-markers-value="<%= @markers.to_json %>"
                >
                </div>
  </div>
        </div>
    </div>


    <div class="back-button">
        <p><a href="/tools">Back to tools</a></p>
    </div>
</div>

app/views/tools/user_show.html.erb
<%= @tool.name %>
<%= @tool.description %>


<p><%= link_to "Back to tools", tools_path %></p>

<p><%= link_to "Delete tool", @tool, method: :delete %></p>

<p><%= link_to "Edit tool details", edit_tool_path(@tool) %></p>


<%# Link to request to book a tool %>
<%= link_to "Book this tool",  new_tool_booking_path(@tool), {:style=>'color: gray;'}%>

<div class="card-product">
  <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
  <div class="card-product-infos">
    <h2>Product name</h2>
    <p>Product description with <strong>relevant info</strong> only.</p>
  </div>
</div>

 <div class="card-info">
      <ul>
          <li>
            <%=link_to t.name, tool_path(t) %>
          </li>
          <li>
            <%= t.tool_type %>
          </li>
          <li>
            <%= t.price %>
          </li>
          <li>
           <%= link_to "Book this tool",  new_tool_booking_path(t), {:style=>'color: gray; padding-left: 1rem;'}%>
          </li>
      </ul>
    </div>